name: Test Server

on:
  push:
  pull_request:

jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start server
        run: |
          nohup python -m navmcp > server.log 2>&1 &
          echo $! > server.pid

      - name: Wait for server to start
        run: sleep 5

      - name: Run pytest
        run: pytest

      - name: Stop server
        run: |
          kill $(cat server.pid)
